### ISSUE TITLE
Breaks for file names containing spaces

### ISSUE THREAD

**Issue by freezy** [sandy98/node-rarfile#1]
Just came across this. On Windows, `unrar` seems to need quotes around the file name when executing. I was able to get it working by wrapping them around `this.archiveName` on [line 127](https://github.com/sandy98/node-rarfile/blob/master/lib/index.js#L127) of the compiled file.

Since you're using coffee script, any way you could add this?

Cheers!

**Comment by sandy98** [comment]
When I stated "This has been recently tested,", this is what I referred to:

In a Windows 2003 server box:

1) npm install rarfile

2) cd node_modules\rarfile\test

3) coffee test_server.coffee (making coffe -c server.coffee and then running node test_server.js works the same)

4) The previous step will fail stating that node-simple-router requirement is not satisfied, so I had to go back and do:
  npm install .  ,  which will install de dev-dependencies. (Just ignore the failure message that states "rm command not found", it's just because that line is meant to run in a *nix system, but will work anyway

5) Run step 3 again. This time the web server will run, but when you point your browser to "localhost:8000", the images won't show. In my case, this happened because UnRAR.exe (such is the name of unrar executable if you install WinRAR) wasn't in the path but in C:\Program Files\WinRar instead.

6) So, I just copied UnRAR.exe to Windows\System32 and after that, things worked smoothly without even restarting the web server. The images shown are contained within "test.cbr", which you will find in test folder.
There's also a test.coffee which you can use like so:

<pre><code>
coffee
coffee>test = require('test')
coffee>test('0.jpg') # this will extract file 0.jpg from test.cbr to the current folder
</code></pre>

All of this worked in Windows 2003 after the preceding steps had been fulfilled.

Now, back to the issue: it's not clear to me if you need to wrap the unrar executable name or,  most likely, the archive name (the only condition that occurs to me would need the latter is if the archive name has spaces within).

In case is the former, keep in mind that RarFile object internally uses this.rarTool to perform its job, so you could either instantiate it like this: <code>var rf = new RarFile(archive_name, {rarTool: whatever_including_quotes_if_it_needs_be});</code> or, once instantiated, do <code>rf.rarTool = whatever..;</code>.

If it's is the latter, just include the needed quotes in the archive name when you instantiate your RarFile object.

So, in my opinion no source code changes should be needed, but anyway just let me know if this solves your issue or not. If it doesn't, I'll be glad to merge a pull request or introduce myself the needed changes.

**Comment by freezy** [comment]
I was referring to the .rar file name of course, and yes, I could pass the file name already wrapped to `rarfile`. However that solution doesn't seem very intuitive to me. It's a one line change really, but if you want I'll submit a PR later.

**Comment by freezy** [comment]
Actually, passing a quote-wrapped filename to `rf.RarFile()` doesn't work, because you're using the same string for `fs.readFileSync()`, which obviously expects a non-wrapped path.

So basically this lib breaks for rar files containing spaces. If you tell me how to do fix this in coffee I'll gladly submit a PR, otherwise I'll greatly appreciate a fix soon. :)

UPDATE: Same problem for executable. When passing an absolute path that contains spaces via the `rarTool` option, it crashes due to executable not found.

**Comment by sandy98** [comment]
You're absolutely right. Having to manually wrap a spaced name with quotes doesn't seem natural.
Besides, I found that the issue you point is not Windows only. It happens just the same on *nix.
I fixed it the way you suggested (see v0.1.13).
I'd appreciate your feedback, so as to close the issue if this is proper.

**Comment by freezy** [comment]
Thanks!

Can't test right now, but the diff looks good. However, I would like to specify the `unrar` executable via a configuration setting instead of forcing users to put it into `PATH`. Your `rarTool` option has the same space issue, maybe that's worth a fix too?

**Comment by sandy98** [comment]
Sounds sensible. 
As soon as I can review it and find a way to do it without breaking anything, it'll be done.
I'll let you know a.s.a.p.

**Comment by sandy98** [comment]
With build 0.1.14-5 I think the whole issue is addressed, so i'm closing it. Should any connected issue arise, please let me know.
